admin_mbo_catalog_module:
  path: /
  methods: [GET]
  defaults:
    _controller: mbo.controller.modules.catalog:indexAction
    _legacy_controller: AdminPsMboModule
    _legacy_link:
      - AdminPsMboModuleParent
      - AdminPsMboModule

admin_mbo_catalog_module_selection:
  path: /selection
  methods: [GET]
  defaults:
    _controller: mbo.controller.modules.selection:indexAction
    _legacy_controller: AdminPsMboSelection
    _legacy_link: AdminPsMboSelection

admin_mbo_module_cdc_error:
  path: /cdc_error
  methods: [ GET ]
  defaults:
    _controller: mbo.controller.modules.catalog:cdcErrorAction
