services:
  _defaults:
    public: true

  PrestaShop\Module\Mbo\Module\SourceRetriever\AddonsUrlSourceRetriever:
    autowire: true
    arguments:
      $addonsDataProvider: '@PrestaShop\Module\Mbo\Addons\Provider\AddonsDataProvider'
      $translator: '@translator'
      $httpClient: '@Psr\Http\Client\ClientInterface'
      $requestFactory: '@Psr\Http\Message\ServerRequestFactoryInterface'
      $configuration: '@PrestaShop\PrestaShop\Core\ConfigurationInterface'
    properties:
      cacheDir: "%kernel.cache_dir%"

  PrestaShop\Module\Mbo\Module\Workflow\TransitionsManager:
    autowire: true

  PrestaShop\Module\Mbo\Module\Workflow\TransitionBuilder:
    autowire: true

  PrestaShop\Module\Mbo\Module\Workflow\TransitionApplier:
    autowire: true

  PrestaShop\Module\Mbo\Module\CommandHandler\ModuleStatusTransitionCommandHandler:
    autowire: true
