services:
  _defaults:
    public: true

  mbo.modules.state_machine:
    class: 'PrestaShop\Module\Mbo\Module\Workflow\ModuleStateMachine'
    arguments:
      - '@event_dispatcher'
      - '@translator'

  mbo.modules.state_machine.source_retriever.url:
    class: 'PrestaShop\Module\Mbo\Module\SourceRetriever\AddonsUrlSourceRetriever'
    arguments:
      $addonsDataProvider: '@mbo.addons.data_provider'
      $translator: '@translator'
      $modulePath: '%modules_dir%'
    properties:
      cacheDir: "%kernel.cache_dir%"

  mbo.modules.state_machine.transitions_manager:
    class: 'PrestaShop\Module\Mbo\Module\Workflow\TransitionsManager'
    arguments:
      - '@PrestaShop\PrestaShop\Core\Module\ModuleManager'

  mbo.modules.state_machine.eventsubscriber.transition:
    class: PrestaShop\Module\Mbo\Module\Workflow\Event\TransitionEventSubscriber
    arguments:
      - '@mbo.modules.state_machine.transitions_manager'
    tags:
      - { name: kernel.event_subscriber }

  mbo.modules.state_machine.module_status_transition_handler:
    class: 'PrestaShop\Module\Mbo\Module\CommandHandler\ModuleStatusTransitionCommandHandler'
    arguments:
      - '@mbo.modules.state_machine'
      - '@mbo.modules.repository'
      - '@mbo.modules.actions_manager'
