services:
  _defaults:
    public: true

  mbo.modules.source_retriever.url:
    class: 'PrestaShop\Module\Mbo\Module\SourceRetriever\AddonsUrlSourceRetriever'
    autowire: true
    arguments:
      - '@mbo.addons.data_provider'
      - '@translator'
      - '@Psr\Http\Client\ClientInterface'
      - '@Psr\Http\Message\ServerRequestFactoryInterface'
      - '@PrestaShop\PrestaShop\Core\ConfigurationInterface'
    properties:
      cacheDir: "%kernel.cache_dir%"

  mbo.modules.transitions_manager:
    class: 'PrestaShop\Module\Mbo\Module\Workflow\TransitionsManager'
    arguments:
      - '@prestashop.module.manager'
      - '@mbo.hook_exception_holder'

  mbo.modules.transition_builder:
    class: PrestaShop\Module\Mbo\Module\Workflow\TransitionBuilder

  mbo.modules.transition_applier:
    class: PrestaShop\Module\Mbo\Module\Workflow\TransitionApplier
    arguments:
      - '@mbo.modules.transitions_manager'

  mbo.modules.module_status_transition_handler:
    class: 'PrestaShop\Module\Mbo\Module\CommandHandler\ModuleStatusTransitionCommandHandler'
    arguments:
      - '@mbo.modules.repository'
      - '@mbo.modules.actions_manager'
      - '@mbo.modules.builder'
      - '@mbo.modules.transition_builder'
      - '@mbo.modules.transition_applier'
