admin_mbo_catalog_module:
  path: /addons/modules/catalog
  methods: [GET]
  defaults:
    _controller: 'PrestaShop\Module\Mbo\Controller\Admin\ModuleCatalogController::indexAction'
    _legacy_controller: AdminPsMboModule
    _legacy_link: AdminPsMboModule

admin_mbo_catalog_module_selection:
  path: /addons/modules/catalog/selection
  methods: [GET]
  defaults:
    _controller: 'PrestaShop\Module\Mbo\Controller\Admin\ModuleSelectionController::indexAction'
    _legacy_controller: AdminPsMboAddons
    _legacy_link: AdminPsMboAddons

admin_mbo_recommended_modules:
  path: /addons/modules/recommended
  methods: [GET]
  defaults:
    _controller: 'PrestaShop\Module\Mbo\Controller\Admin\ModuleRecommended::indexAction'
    _legacy_controller: AdminPsMboAddons
    _legacy_link: AdminPsMboAddons:recommendedModules

admin_mbo_catalog_theme:
  path: /addons/themes/catalog
  methods: [GET]
  defaults:
    _controller: 'PrestaShop\Module\Mbo\Controller\Admin\ThemeCatalogController::indexAction'
    _legacy_controller: AdminPsMboTheme
    _legacy_link: AdminPsMboTheme
